### PR TITLE
Model reorg

### PR DESCRIPTION
**Pull request by karllark**
All should be good and the models reorged.
Addresses #24.
@dcorre : can you give this a look over and tell me if it makes sense?

### CODE REVIEW

**Comment by dcorre** [comment]
It seems very nice. It looks like we have now a nice skeleton for the project!
Need to add more models now :)

**Comment by karllark** [comment]
Yep.  Still need those tests.  :-)

**Comment by dcorre** [comment]
Useful reminder :) I should be able to work on it later on this week

**Comment by karllark** [comment]
Yeah!

**Pull request merged**
