### PR TITLE
Expanding the documentation

### PR DESCRIPTION
**Pull request by karllark**
Hopefully making things better.

### CODE REVIEW

**Comment by karllark** [comment]
Will merge this in a day or two.  Trying to keep the momentum going.

**Comment by dcorre** [comment]
Hi Karl, I agree that plotting the unnormalised curves makes more sense.
The y label is not correct as the C00 dots are A(x)/1.086 the WG00 attenuation curves are tau(x). However as you mentioned in one of the issues, I also prefer that each module returns A(x) per default. So the y label should remain Att(x). 
Can you divide the output of the WG00 model by 1.086 to go from tau(x) to A(x)? And then delete the      y /= 1.086  at line 98 in fit_attenuation.rst ?
It will not change the new documentation you have written as you already use Att(x) as the y label.

**Comment by karllark** [comment]
Done.  Good catch on the C00!

**Comment by karllark** [comment]
Might solve #20.

**Comment by karllark** [comment]
Note that the WG00 does not need to be multiplied by 1.086 since we are fitting to the C00 model in Att units.  Thus, the fitted value reported at tau_V is actually the best fit Att(V) and the best fit model is then effectively in Att(x) units.  This is because the scaling between tau_V and Att(V) is a constant.

**Pull request merged**
